In [2]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv("raw_combined2.csv", encoding = 'cp949', sep = ',')

In [43]:
df.columns

Index(['Company:', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30'],
      dtype='object')

In [44]:
skip = df.index[df.iloc[:,0].str.contains('Data', na = False)].to_list()

In [45]:
skip

[14]

In [46]:
df.drop(df.index[0:skip[0]+1], inplace = True)
df.drop(df.columns[0:2], axis = 1, inplace = True)

In [47]:
df

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
15,시간_1Hz,1.T_OC IN,2.T_OC OUT,3.T_BAT 상 표면,4.T_BAT 상 표면 sealed,5.T_BAT 상 주변공기,6.T_BAT 전 표면,7.T_BAT 전 주변공기,8.T_BAT 우 표면,9.T_BAT 우 주변공기,...,EnginePercentLoadAtCurrentSpeed,ActualEnginePercentTorque,EngineSpeed,EngineCoolantTemperature,EngineFuelTemperature1,EngineOilTemperature1,EngineFuelDeliveryPressure,EngineOilPressure,EngineFuelRate,FanSpeed
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,(s),(°C),(°C),(°C),(°C),(°C),(°C),(°C),(°C),(°C),...,(%),(%),(rpm),(deg C),(deg C),(deg C),(kPa),(kPa),(l/h),(rpm)
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0.940537,28.1980621,28.98359655,19.60082399,19.03349355,22.65568017,18.1170367,17.50606546,18.2043183,18.33524071,...,NOVALUE,NOVALUE,1305,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2403,79,NOVALUE,NOVALUE,NOVALUE,200,NOVALUE,NOVALUE
10016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2405,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
10017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2404,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
10018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2400,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
10019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2401,NOVALUE,NOVALUE,NOVALUE,NOVALUE,200,NOVALUE,NOVALUE

In [50]:
new_header = df.iloc[0]

In [54]:
df.columns = new_header

In [61]:
df.drop(df.index[0], inplace = True)

In [65]:
df.drop(df.index[[0,2]], inplace = True)

In [81]:
ones = df.columns.str.contains("1Hz")
tens = df.columns.str.contains("10Hz")
hundreds = df.columns.str.contains("100Hz")
thousands = df.columns.str.contains("1000Hz")

In [84]:
print(ones.nonzero(), tens.nonzero(), hundreds.nonzero(), thousands.nonzero())

(array([0], dtype=int64),) (array([17], dtype=int64),) (array([], dtype=int64),) (array([], dtype=int64),)

In [85]:
df

15,시간_1Hz,1.T_OC IN,2.T_OC OUT,3.T_BAT 상 표면,4.T_BAT 상 표면 sealed,5.T_BAT 상 주변공기,6.T_BAT 전 표면,7.T_BAT 전 주변공기,8.T_BAT 우 표면,9.T_BAT 우 주변공기,...,EnginePercentLoadAtCurrentSpeed,ActualEnginePercentTorque,EngineSpeed,EngineCoolantTemperature,EngineFuelTemperature1,EngineOilTemperature1,EngineFuelDeliveryPressure,EngineOilPressure,EngineFuelRate,FanSpeed
17,(s),(°C),(°C),(°C),(°C),(°C),(°C),(°C),(°C),(°C),...,(%),(%),(rpm),(deg C),(deg C),(deg C),(kPa),(kPa),(l/h),(rpm)
19,0.940537,28.1980621,28.98359655,19.60082399,19.03349355,22.65568017,18.1170367,17.50606546,18.2043183,18.33524071,...,NOVALUE,NOVALUE,1305,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
20,1.940537,28.1544213,28.93995575,19.51354238,18.98985275,22.56839857,18.1170367,17.46242466,18.2043183,18.37888151,...,NOVALUE,NOVALUE,1304,NOVALUE,NOVALUE,NOVALUE,NOVALUE,200,NOVALUE,NOVALUE
21,2.940537,28.1980621,28.98359655,19.51354238,19.03349355,22.52475776,18.0733959,17.46242466,18.2043183,18.37888151,...,NOVALUE,NOVALUE,1300,NOVALUE,NOVALUE,NOVALUE,NOVALUE,200,NOVALUE,NOVALUE
22,3.940537,28.1980621,28.98359655,19.51354238,19.03349355,22.52475776,18.1170367,17.37514305,18.2043183,18.33524071,...,NOVALUE,NOVALUE,1303,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2403,79,NOVALUE,NOVALUE,NOVALUE,200,NOVALUE,NOVALUE
10016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2405,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
10017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2404,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
10018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2400,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE,NOVALUE
10019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NOVALUE,NOVALUE,2401,NOVALUE,NOVALUE,NOVALUE,NOVALUE,200,NOVALUE,NOVALUE

In [87]:
df.replace("          NOVALUE", np.nan, inplace = True)

In [88]:
df

15,시간_1Hz,1.T_OC IN,2.T_OC OUT,3.T_BAT 상 표면,4.T_BAT 상 표면 sealed,5.T_BAT 상 주변공기,6.T_BAT 전 표면,7.T_BAT 전 주변공기,8.T_BAT 우 표면,9.T_BAT 우 주변공기,...,EnginePercentLoadAtCurrentSpeed,ActualEnginePercentTorque,EngineSpeed,EngineCoolantTemperature,EngineFuelTemperature1,EngineOilTemperature1,EngineFuelDeliveryPressure,EngineOilPressure,EngineFuelRate,FanSpeed
17,(s),(°C),(°C),(°C),(°C),(°C),(°C),(°C),(°C),(°C),...,(%),(%),(rpm),(deg C),(deg C),(deg C),(kPa),(kPa),(l/h),(rpm)
19,0.940537,28.1980621,28.98359655,19.60082399,19.03349355,22.65568017,18.1170367,17.50606546,18.2043183,18.33524071,...,NaN,NaN,1305,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1.940537,28.1544213,28.93995575,19.51354238,18.98985275,22.56839857,18.1170367,17.46242466,18.2043183,18.37888151,...,NaN,NaN,1304,NaN,NaN,NaN,NaN,200,NaN,NaN
21,2.940537,28.1980621,28.98359655,19.51354238,19.03349355,22.52475776,18.0733959,17.46242466,18.2043183,18.37888151,...,NaN,NaN,1300,NaN,NaN,NaN,NaN,200,NaN,NaN
22,3.940537,28.1980621,28.98359655,19.51354238,19.03349355,22.52475776,18.1170367,17.37514305,18.2043183,18.33524071,...,NaN,NaN,1303,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2403,79,NaN,NaN,NaN,200,NaN,NaN
10016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2405,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2404,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2401,NaN,NaN,NaN,NaN,200,NaN,NaN

In [89]:
df.reindex(

15,시간_1Hz,1.T_OC IN,2.T_OC OUT,3.T_BAT 상 표면,4.T_BAT 상 표면 sealed,5.T_BAT 상 주변공기,6.T_BAT 전 표면,7.T_BAT 전 주변공기,8.T_BAT 우 표면,9.T_BAT 우 주변공기,...,EnginePercentLoadAtCurrentSpeed,ActualEnginePercentTorque,EngineSpeed,EngineCoolantTemperature,EngineFuelTemperature1,EngineOilTemperature1,EngineFuelDeliveryPressure,EngineOilPressure,EngineFuelRate,FanSpeed
17,(s),(°C),(°C),(°C),(°C),(°C),(°C),(°C),(°C),(°C),...,(%),(%),(rpm),(deg C),(deg C),(deg C),(kPa),(kPa),(l/h),(rpm)
19,0.940537,28.1980621,28.98359655,19.60082399,19.03349355,22.65568017,18.1170367,17.50606546,18.2043183,18.33524071,...,NaN,NaN,1305,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1.940537,28.1544213,28.93995575,19.51354238,18.98985275,22.56839857,18.1170367,17.46242466,18.2043183,18.37888151,...,NaN,NaN,1304,NaN,NaN,NaN,NaN,200,NaN,NaN
21,2.940537,28.1980621,28.98359655,19.51354238,19.03349355,22.52475776,18.0733959,17.46242466,18.2043183,18.37888151,...,NaN,NaN,1300,NaN,NaN,NaN,NaN,200,NaN,NaN
22,3.940537,28.1980621,28.98359655,19.51354238,19.03349355,22.52475776,18.1170367,17.37514305,18.2043183,18.33524071,...,NaN,NaN,1303,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2403,79,NaN,NaN,NaN,200,NaN,NaN
10016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2405,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2404,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2401,NaN,NaN,NaN,NaN,200,NaN,NaN