In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("948_VDC14R at normal load.csv")

In [20]:
df

,Time_1Hz,17.T_Engine Room,18.T_Engine Room 2,19.T_Engine Room Surface,20.T_Fan Guard Around,21.T_NOx Sensor Down Under,1.T_Air,2.T_DP Sensor Surface Up,4.T_DP Sensor Surface Down,5.T_DP Sensor Surface In,...,7.T_DP Sensor Under,8.T_NOx Sensor Up Above,9.T_NOx Sensor Up Surface,10.T_NOx Sensor Up Around,11.T_Reservoir Around Left,12.T_Reservoir Around Right,13.T_NOx Sensor Down Surface,14.T_NOx Sensor Down Around,15.T_DM Surface,16.T_DM Around
Time,,,,,,,,,,,,,,,,,,,,,
1970-01-01 00:00:00.000000000,0.575881,70.355077,74.282750,77.948577,69.613184,82.792706,46.963607,81.352560,81.308919,81.352560,...,80.654307,79.476005,81.090715,76.115663,80.479744,79.432364,85.672999,83.229114,81.658045,78.341344
1970-01-01 00:00:00.000000001,1.575881,70.355077,74.151827,77.948577,69.525902,82.749065,46.876326,81.352560,81.308919,81.308919,...,80.872511,79.519646,81.047074,75.984741,80.741588,79.388724,85.672999,83.229114,81.614405,78.341344
1970-01-01 00:00:00.000000002,2.575881,70.398718,74.108186,77.948577,69.482261,82.749065,46.570840,81.352560,81.308919,81.352560,...,80.872511,79.301442,81.047074,76.028382,80.610666,79.345083,85.716640,83.272755,81.527123,78.297704
1970-01-01 00:00:00.000000003,3.575881,70.267796,74.151827,77.948577,69.351339,82.705425,46.614481,81.352560,81.308919,81.352560,...,81.177996,79.301442,81.047074,76.159304,80.654307,79.170520,85.672999,83.229114,81.439841,78.210422
1970-01-01 00:00:00.000000004,4.575881,70.355077,73.889982,78.035859,69.438621,82.749065,46.701762,81.396201,81.308919,81.308919,...,81.047074,79.476005,81.003433,76.159304,80.348821,79.257801,85.629358,83.141833,81.352560,78.035859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970-01-01 00:00:00.000005590,5590.575881,83.621881,77.293965,94.401160,77.032120,92.961013,45.610742,97.019608,95.186694,101.383688,...,87.724117,81.483482,81.090715,59.183032,86.720378,86.851301,88.727855,76.028382,92.742809,88.815137
1970-01-01 00:00:00.000005591,5591.575881,83.665522,77.250324,94.401160,76.944839,93.004654,45.610742,96.975967,95.186694,101.383688,...,87.593194,81.439841,81.134356,58.790265,86.851301,86.894942,88.858778,76.115663,93.353780,88.596933
1970-01-01 00:00:00.000005592,5592.575881,83.578241,77.206683,94.357519,76.944839,92.961013,45.610742,97.019608,95.186694,101.252766,...,87.811398,81.614405,81.265278,59.401236,86.851301,86.633097,88.902419,76.377508,94.095674,89.207904
1970-01-01 00:00:00.000005593,5593.575881,83.665522,77.250324,94.401160,77.032120,92.961013,45.698024,97.019608,95.143053,101.252766,...,87.767758,81.308919,81.221637,59.881285,86.720378,86.589456,88.946059,76.552071,94.226596,89.469749
1970-01-01 00:00:00.000005594,5594.575881,83.621881,77.075761,94.357519,76.901198,92.961013,45.610742,96.975967,95.143053,101.209125,...,87.636835,81.177996,81.265278,59.924926,86.807660,86.764019,88.989700,76.813916,94.270237,89.207904

In [9]:
df['Time'] = pd.to_datetime(df['Time_1Hz'])

In [10]:
df.head()

,Time_1Hz,17.T_Engine Room,18.T_Engine Room 2,19.T_Engine Room Surface,20.T_Fan Guard Around,21.T_NOx Sensor Down Under,1.T_Air,2.T_DP Sensor Surface Up,4.T_DP Sensor Surface Down,5.T_DP Sensor Surface In,...,8.T_NOx Sensor Up Above,9.T_NOx Sensor Up Surface,10.T_NOx Sensor Up Around,11.T_Reservoir Around Left,12.T_Reservoir Around Right,13.T_NOx Sensor Down Surface,14.T_NOx Sensor Down Around,15.T_DM Surface,16.T_DM Around,Time
0,0.575881,70.355077,74.282750,77.948577,69.613184,82.792706,46.963607,81.352560,81.308919,81.352560,...,79.476005,81.090715,76.115663,80.479744,79.432364,85.672999,83.229114,81.658045,78.341344,1970-01-01 00:00:00.000000000
1,1.575881,70.355077,74.151827,77.948577,69.525902,82.749065,46.876326,81.352560,81.308919,81.308919,...,79.519646,81.047074,75.984741,80.741588,79.388724,85.672999,83.229114,81.614405,78.341344,1970-01-01 00:00:00.000000001
2,2.575881,70.398718,74.108186,77.948577,69.482261,82.749065,46.570840,81.352560,81.308919,81.352560,...,79.301442,81.047074,76.028382,80.610666,79.345083,85.716640,83.272755,81.527123,78.297704,1970-01-01 00:00:00.000000002
3,3.575881,70.267796,74.151827,77.948577,69.351339,82.705425,46.614481,81.352560,81.308919,81.352560,...,79.301442,81.047074,76.159304,80.654307,79.170520,85.672999,83.229114,81.439841,78.210422,1970-01-01 00:00:00.000000003
4,4.575881,70.355077,73.889982,78.035859,69.438621,82.749065,46.701762,81.396201,81.308919,81.308919,...,79.476005,81.003433,76.159304,80.348821,79.257801,85.629358,83.141833,81.352560,78.035859,1970-01-01 00:00:00.000000004

In [18]:
def align_time_series(df, freq='1S'):
    df.set_index('Time', inplace=True)
    resampled_df = df.resample(freq).mean().interpolate()
    return resampled_df.reset_index()

In [13]:
df2 = df.apply(pd.to_numeric, errors='coerce')

In [14]:
df2.head()

,Time_1Hz,17.T_Engine Room,18.T_Engine Room 2,19.T_Engine Room Surface,20.T_Fan Guard Around,21.T_NOx Sensor Down Under,1.T_Air,2.T_DP Sensor Surface Up,4.T_DP Sensor Surface Down,5.T_DP Sensor Surface In,...,8.T_NOx Sensor Up Above,9.T_NOx Sensor Up Surface,10.T_NOx Sensor Up Around,11.T_Reservoir Around Left,12.T_Reservoir Around Right,13.T_NOx Sensor Down Surface,14.T_NOx Sensor Down Around,15.T_DM Surface,16.T_DM Around,Time
0,0.575881,70.355077,74.282750,77.948577,69.613184,82.792706,46.963607,81.352560,81.308919,81.352560,...,79.476005,81.090715,76.115663,80.479744,79.432364,85.672999,83.229114,81.658045,78.341344,0
1,1.575881,70.355077,74.151827,77.948577,69.525902,82.749065,46.876326,81.352560,81.308919,81.308919,...,79.519646,81.047074,75.984741,80.741588,79.388724,85.672999,83.229114,81.614405,78.341344,1
2,2.575881,70.398718,74.108186,77.948577,69.482261,82.749065,46.570840,81.352560,81.308919,81.352560,...,79.301442,81.047074,76.028382,80.610666,79.345083,85.716640,83.272755,81.527123,78.297704,2
3,3.575881,70.267796,74.151827,77.948577,69.351339,82.705425,46.614481,81.352560,81.308919,81.352560,...,79.301442,81.047074,76.159304,80.654307,79.170520,85.672999,83.229114,81.439841,78.210422,3
4,4.575881,70.355077,73.889982,78.035859,69.438621,82.749065,46.701762,81.396201,81.308919,81.308919,...,79.476005,81.003433,76.159304,80.348821,79.257801,85.629358,83.141833,81.352560,78.035859,4

In [19]:
align_time_series(df)

,Time,Time_1Hz,17.T_Engine Room,18.T_Engine Room 2,19.T_Engine Room Surface,20.T_Fan Guard Around,21.T_NOx Sensor Down Under,1.T_Air,2.T_DP Sensor Surface Up,4.T_DP Sensor Surface Down,...,7.T_DP Sensor Under,8.T_NOx Sensor Up Above,9.T_NOx Sensor Up Surface,10.T_NOx Sensor Up Around,11.T_Reservoir Around Left,12.T_Reservoir Around Right,13.T_NOx Sensor Down Surface,14.T_NOx Sensor Down Around,15.T_DM Surface,16.T_DM Around
0,1970-01-01,2797.575881,81.197052,82.474358,87.81767,78.397566,89.212218,44.397037,90.513649,90.314119,...,90.958591,85.920921,85.188411,77.298232,90.332651,88.312687,92.464967,88.882061,88.747316,89.069275